### ISSUE TITLE
Exception thrown in __init__ causes onrecoverable error

### ISSUE THREAD

**Issue by rmadsen-ks** [opentap/OpenTap.Python#118]
Here is some buggy code:

```py
class BaseClassExample(OpenTap.TestStep):
    
    Str1 = property(String, "127.0.0.1")\
        .add_attribute(OpenTap.Display("Str on base class.", "The IP Address of the instrument."))
    def __init__(self):
        print(Str1)
        super().__init__()
        
    def Run(self):
        """Called by TAP when the test plan ends."""
        super().Run()
```

When __init__() is called, Print(Str1) throws an exception because i forgot to call self.Str1. 

This causes an exception in the finalizer in the GC thread, which causes the program to crash.

```
 ArgumentNullException: Value cannot be null.Parameter name: derived
     at Python.Runtime.Finalizer.AddDerivedFinalizedObject(IntPtr& derived, Int32 run)
     at Python.Runtime.PythonDerivedType.PyFinalize(IPythonDerivedType obj)
     at PythonExamples.InheritExample.BaseClassExample.Finalize()
 Exception caught at:
     at Void AddDerivedFinalizedObject(IntPtr ByRef, Int32)
     at Void PyFinalize(Python.Runtime.IPythonDerivedType)
     at Void Finalize()
```

Probably we need to catch the exception and prevent a degenerate object from being created in the first place. This needs to be fixed in Pythonnet.

**Comment by rmadsen-ks** [comment]
Note: Consider suppressing finalize when an exception is thrown from the constructor.
